#!/usr/bin/env node

var cmd = require('commander');
var async = require('async');

cmd
  .version('0.0.1')
  .usage('[action] <ip>')
  .option('-k, --keys', 'Install public ssh keys')
  .option('-u, --user', 'Create deploy user')
  .option('-i, --install', 'Install software')
  .option('-e, --environment <config>', 'Push .env.json file')
  .option('-s, --service', 'Create the service')
  .option('-r, --remote <name>', 'Add remote for git push')
  .option('-a, --all', 'Perform all provisioning steps');

cmd.on('--help', function(){
  console.log('  Actions:');
  console.log('');
  console.log('    $ provision -a 1.2.3.4 config/web.stack.json');
  console.log('');
});

cmd.parse(process.argv);
