#!/usr/bin/env bash

VERSION="0.1.0"

echo "Creating /assets..."
mkdir -p assets

echo "Creating /logs..."
mkdir -p logs

echo "Creating /pids..."
mkdir -p pids

echo "Creating /scripts/keys..."
mkdir -p scripts/keys

echo "Running npm install..."
npm install

echo "Done."
echo ""
echo "You should test your boilerplate app with 'sudo node server.js'"