#!/usr/bin/env bash

ok() {
  #echo "`put setaf 2` $@ `tput setaf 7`"
  echo "$@"
}

maybe() {
  #echo "`tput setaf 3` $@ `tput setaf 7`"
  echo "$@"
}

no() {
  #echo "`tput setaf 1` $@ `tput setaf 7`"
  echo "$@"
}

check() {
  requirement=$1
  desired=$3
  version=$($2 2>&1)
  if [ "$version" = "$desired" ]
  then
    ok "  $requirement: OK"
  elif [[ $version == *command* ]]
  then
    no "  $requirement: NOT AVAILABLE"
  else
    maybe "  $requirement: MAYBE"
    maybe "  suggested: $desired"
    maybe "  system has: $version"
  fi
  echo "  ---"
}

echo "  ---"
check "node" "node --version" "v0.6.8"
check "redis" "redis-server --version" "Redis server version 2.4.5 (00000000:0)"
check "mongo" "mongo --version" "MongoDB shell version: 2.0.2"
